clangd/clangd

- README.md
We already have some communication channels that can be used to help our
users, but they are not very discoverable. Adding several links to the
README might help us to reach more Clangd users.
> Add references to other communication channels

- .github/workflows/autobuild.yaml
Use of the standard FindZLIB and thus support for ZLIB_LIBRARIES was
removed upstream in llvm/llvm-project@916be8fd6a0a0feea4cefcbeb0c22c65848d7a2e
> Fix static linking of zlib.

- .github/workflows/autobuild.yaml
- .github/workflows/lib_compat.h
They're binary-compatible, the old versions are more widely available
and the new versions are more highly optimized. We prefer the former.
> Link against older, more-compatible versiosn of glibc symbols

- .github/workflows/autobuild.yaml
- .github/workflows/lib_compat_test.py
- releases.md
This regressed twice over the last two months (new floating point
function versions, and accidental dynamic linking against zlib).
We also want to avoid regressions when merging remote index.
The test is able to do a little bit more than we use in the automated
build (the --sym flag is unused, as is unversioned --lib=GLIBC) but they're
pretty useful when experimenting with how to fix things!
We run the test right at the end, because if it fails we want to be able
to download the binary artifact and inspect it.
Unfortunately by the nature of the test we can only run it when we
produce a build, so currently weekly.
Tested **locally**: this passes in with #370 and #371 merged, and fails when either is missing. If it fails in prod, I'm fairly sure it's catching a real bug.
> Test that linux binary depends on glibc 2.18 and no other dynamic symbols

- .github/workflows/autobuild.yaml
Set the flag to 10.9 (the same version of LLVM [official release](https://llvm.org/docs/ReleaseProcess.html#test-release-sh))
Make sure we support older version of macOS (10.9+) when building clangd with
the latest macOS (10.15).
Fixes #505
> Set MACOSX_DEPLOYMENT_TARGET flag.

- .github/workflows/autobuild.yaml
- .github/workflows/periodic.yaml
Environment files are to be used instead now:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Remove deprecated set-env command

- .github/workflows/autobuild.yaml
Start building clangd with remote index support on Linux.
> Enable gRPC support for clangd on Linux

- .github/workflows/autobuild.yaml
They are needed for correct indexing.
> Bundle headers in indexing-tools release archive

- .github/workflows/periodic.yaml
Release names contains quotes around commit hashes due to the escaping.
After this patch, they'll be gone.
> Change escaping of double quotes to single quote

- .github/workflows/autobuild.yaml
This is the same version we are using in our buildbot, so this will
surely be the "stable" version for us right now.
> Bump gRPC version to 1.33.2

- .github/workflows/autobuild.yaml
MSVC version is now 16.7+, see
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
> Remove obsolete compiler hack from windows build config.

- .github/workflows/autobuild.yaml
Artifacts are used to pass data from one job to another but we upload
release assets in the same job we build them, hence artifacts are
redundant.
> Do not upload artifacts in autobuild job

- .github/workflows/autobuild.yaml
- .github/workflows/lib_compat.h
While building clangd binaries we set required glibc version for symbols
to a minimum to cover systems with older glibc implementations. But we
were not doing that while building gRPC, which might depend on never
versions of these symbols.
> Include lib_compat.h while building gRPC

- .github/workflows/autobuild.yaml
There's pthread_cond_clockwait@GLIBC_2.30 introduced with new glibc,
which isn't available in older versions. To prevent such breakages we
are sticking to ubuntu-18 rather than moving to ubuntu-20.
For a sample error see
https://github.com/kadircet/clangd/runs/2011039246?check_suite_focus=true.
Version label grabbed from
https://github.com/actions/virtual-environments.
> Use ubuntu-18 for older glibc

- .github/workflows/autobuild.yaml
Extract the repository from the commit message. This will help us have more control over the release process.
> Allow using a different repository for the manual release

- .github/workflows/autobuild.yaml
This allows autoupdate to work in our buggy clients.
See https://github.com/clangd/vscode-clangd/issues/180
Stylistic justification: "clangd_indexing_tools" is one "word" in the
"name-platform-version.zip" naming convention.
> Rename clangd-indexing-tools-platform-version.zip -> clangd_indexing_tools-platform-version.zip

- .github/workflows/autobuild.yaml
Builds started to fail
(https://github.com/clangd/clangd/runs/2595990099?check_suite_focus=true)
because Abseil source file (built as a part of gRPC) was using
`std::numeric_limits` and `uint32_t` but not including `<limits>` and
`<cstdint>` directly
(https://github.com/abseil/abseil-cpp/blob/df3ea785d8c30a9503321a3d35ee7d35808f190d/absl/synchronization/internal/graphcycles.cc).
This worked with libstdc++ 10 but GitHub Actions recently updated the
toolchain for Ubuntu 18.04 LTS we're using
(https://github.com/actions/virtual-environments/commit/0409144182dc17ad9bed72886ba4aa3506cf8a6d#diff-8d528b68ca937dfe5a0194829f0eb2633bc3d7a3105a637ccb534a4da765f7a3R17).
libstdc++ 11 changed the standard headers and is now less forgiving when
it comes to `<limits>` and few other headers not being …
> Bump gRPC version: 1.33.2 -> 1.36.3

- .github/workflows/autobuild.yaml
Fixes https://github.com/clangd/vscode-clangd/issues/228
> Explicitly set OSX_DEPLOYMENT_TARGET in cmake flags, as matrix.config.env is not propagated into job's env variables.

- .github/ISSUE_TEMPLATE/config.yaml
That will increase the visibility of the Discussions mechanism.
Also, make it impossible to open empty bug reports.
> Link to GitHub Discussions when opening an issue

- .github/workflows/autobuild.yaml
Fixes #971
Tested as https://github.com/sam-mccall/clangd/actions/runs/1638606157
(Oops, it failed in the end because of no credentials to upload the final zip)
> Include omp.h in the clangd release packages

- .github/workflows/autobuild.yaml
Because in https://github.com/llvm/llvm-project/pull/66850 the deprecated `LLVM_USE_CRT_*` was removed the weekly build failed with the observed linking issues. 
This PR attempts to fix that by using CMake's `CMAKE_MSVC_RUNTIME_LIBRARY`.
> Fix runtime linkage on windows

- .github/workflows/autobuild.yaml
This #2028 is because the macos-latest image was upgraded from macos-12 to macos-14, resulting in AppleClang being updated from version 14 to 15. To resolve the problem, simply modify macos-latest back to macos-12.
Additionally, the Linux build now requires Python 3.8 and the ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION environment variable enabled. I have also addressed these issues.
I forked one and fixed compilation issues on both macOS and Linux platforms. Now GitHub Actions are working fine.
> Fix Weekly snapshot releases

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/autobuild.yaml
This could help with dumping human-readable backtrace symbols with line no.
See also #1641.
> Build PDB file for Windows

- .github/workflows/autobuild.yaml
The macos-12 image has been removed in https://github.com/actions/runner-images/issues/10721.
Fixes https://github.com/clangd/clangd/issues/2245
> Use macos-13 image for Mac builds

- .github/workflows/autobuild.yaml
v3 has been deprecated and removed (https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
Fixes https://github.com/clangd/clangd/issues/2305
> Use upload-artifact@v4 and download-artifact@v4 actions

- .github/workflows/autobuild.yaml
It seems the MacOS CI build has failed for 2 weeks
The error output is 
```
FAILED: tools/clang/lib/Tooling/DependencyScanning/CMakeFiles/obj.clangDependencyScanning.dir/DependencyScanningService.cpp.o 
/usr/bin/clang++ -DCLANG_EXPORTS -DGTEST_HAS_RTTI=0 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/Users/runner/work/clangd/clangd/clangd_snapshot_20250330/tools/clang/lib/Tooling/DependencyScanning -I/Users/runner/work/clangd/clangd/llvm-project/clang/lib/Tooling/DependencyScanning -I/Users/runner/work/clangd/clangd/llvm-project/clang/include -I/Users/runner/work/clangd/clangd/clangd_snapshot_20250330/tools/clang/include -I/Users/runner/work/clangd/clangd/clangd_snapshot_20250330/include -I/Users/runner/work/clangd/clangd/llvm-project/llvm/include -fPIC …
```
> Fix MacOS CI builds

- .github/workflows/autobuild.yaml
Fix #2415. It seems that upgrading clang-9 to clang-10 in the Linux CI configuration could resolve the compilation errors.
> Upgrade clang version from clang-9 to clang-10 in Linux workflow

- .github/workflows/autobuild.yaml
Fix https://github.com/clangd/clangd/issues/2439. It seems that upgrading Windows' Actions runner version from Windows-2019 to Windows-2022 in the Windows CI configuration could resolve the compilation errors.
> Fix Windows CI builds.

- .github/workflows/autobuild.yaml
It seems that clients are checking filename prefixes for updating, and having two archives with the same prefix did confuse the clients.
Fixes https://github.com/clangd/node-clangd/issues/39
> [CI] Rename debug symbol names to avoid name confusing
